on: push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: danger/danger-js@9.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: true
