on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew build assembleDebugAndroidTest # "build" includes lint and test.
      - run: ./gradlew assembleRelease
      - uses: danger/danger-js@9.1.8
