on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: ./gradlew ktlintCheck
      - run: |
          gem install bundler
          bundle install
          danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }} # Instead, use ${{ secrets.GITHUB_TOKEN }} if you don't have to use a bot.
