on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: ./gradlew ktlintCheck
      - run: |
          gem install bundler
          bundle install
          danger
        env:
          # Use the following if you want a bot account to comment on the pull request.
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }} // A bot account's personal access token that has full access to repo.
          # Otherwise, use the following.
          # DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
