on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: ./gradlew ktlintCheck
      - run: |
          gem install bundler
          bundle install
      - run: bundle exec danger
        env:
          # Use the following if you want a bot account.
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
          # Otherwise, use the following.
          # DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
