on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: ./gradlew build assembleDebugAndroidTest # "build" includes lint and test.
    - uses: actions/upload-artifact@v1
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
    - uses: actions/upload-artifact@v1
      with:
        name: app-debug-androidTest
        path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
  firebase:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: app-debug
      - uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_BASE64 }}
      - run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}
      - run: gcloud firebase test android run --type instrumentation --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk　--device model=flame
